name: properties-types-tests
version: '0.0.0'
author: Scott Murphy <scottmurphy09@gmail.com>
maintainer: Scott Murphy <scottmurphy09@gmail.com>
license: BSD3
git: ''
extra-source-files:
- README.md
- ChangeLog.md
dependencies:
  - base >=4 && <5
  - lens
library:
  source-dirs: src
  ghc-options: -Wall
  exposed-modules:
  - Example.Properties
  - Example.Properties.Internal

executables:
  properties-types-tests:
    main: Main.hs
    source-dirs: src
    ghc-options: -Wall -threaded -O2
    dependencies:
      - optparse-generic
tests:
  spec:
    main: Spec.hs
    source-dirs:
    - src
    - test
    ghc-options: -Wall -threaded
    dependencies:
    - regex-genex
    - tasty
    - tasty-golden
    - tasty-hunit
    - tasty-quickcheck
    - QuickCheck
