flags: {}
extra-package-dbs: []
packages:
- '.'
- location:
    git: https://github.com/ucsd-progsys/liquidhaskell.git
    commit: 300524229e49c50d8842e191fdb7e1d537853019
  subdirs: []
  extra-dep: true
  
extra-deps:
- herf-time-0.2.2
- regex-genex-0.7.0
- stream-monad-0.3
resolver: lts-7.9
